export const types = {
  Container: Symbol.for("ioc-container"),
  IHttpService: Symbol.for("IHttpService"),
  ILogService: Symbol.for("ILogService"),
  IWebBrowserService: Symbol.for("IWebBrowserService"),
  IUtilService: Symbol.for("IUtilService"),
  IReflectionService: Symbol.for("IReflectionService"),
  IFlowService: Symbol.for("IFlowService"),
  IDomainService: Symbol.for("IDomainService"),
  ILinkService: Symbol.for("ILinkService"),
  IProcessService: Symbol.for("IProcessService"),
  IScraperService: Symbol.for("IScraperService"),
  IQueueService: Symbol.for("IQueueService"),
  IContactService: Symbol.for("IContactService"),
};
